---
name: Bug report
about: Create a report to help us improve
title: '[BUG] '
labels: bug
assignees: ''

---

**Device Information**
- Model: P110
- Firmware Version: [e.g., 1.1.3 Build 240523 Rel.175054]
- IP Address: [e.g., 192.168.1.100]

**Environment**
- OctoPrint Version: [e.g., 1.9.3]
- Python Version: [e.g., 3.11.5]
- Operating System: [e.g., Raspberry Pi OS, Ubuntu 22.04]

**Plugin Information**
- Plugin Version: [e.g., 1.0.0]
- PSU Control Version: [e.g., 1.1.2]

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Actual behavior**
A clear and concise description of what actually happened.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Logs**
Please include relevant log entries from OctoPrint:
```
[Paste log entries here]
```

**Additional context**
Add any other context about the problem here.

**Troubleshooting attempted**
- [ ] Ran test_plugin.py script
- [ ] Checked network connectivity to P110
- [ ] Verified Tapo credentials
- [ ] Restarted OctoPrint
- [ ] Checked OctoPrint logs
- [ ] Other: [describe]
